 
name: LitmusDocs-CI
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  embedmd:
    runs-on: ubuntu-latest
    steps:

      #Using the last commit id of pull request
      - uses: octokit/request-action@v2.x
        id: get_PR_commits
        with:
          route: GET /repos/:repo/pulls/:pull_number/commits
          repo: ${{ github.repository }}
          pull_number: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: set commit to output
        id: getcommit
        run: | 
           prsha=$(echo $response | jq '.[-1].sha'  | tr -d '"')
           echo "::set-output name=sha::$prsha" 
        env: 
          response:  ${{ steps.get_PR_commits.outputs.data }}
          
      - uses: actions/checkout@v2
        with:
          ref: ${{steps.getcommit.outputs.sha}}      

      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.14.0'

      - name: Installing and Running embedmed
        run: |
          go get github.com/campoy/embedmd
          cd docs
          embedmd -w $(find *.md)
        continue-on-error: true  
        
      - name: embedmd check
        run: |
          count=$(git diff | wc -l)
          if [ "$count" -eq "0" ]
          then
            echo "embedmd check failed\nThese files need to run embedmd once:"
            git diff
            echo "Please follow the instructions to run embedmd:"
            echo "cd docs\nembedmd -w $(find *.md)"
            echo "For more info visit https://github.com/litmuschaos/litmus-docs/blob/master/CONTRIBUTING.md"
            exit 1
          else
            echo "Nothing to embed"
          fi
        shell: sh
